### ISSUE TITLE
Dell Latitude E6420 (macOS BigSur)

### ISSUE THREAD

**Issue by HimanshuRane** [Mo-6420/MoNo#1]
I used ur EFI but it didnt work like is this one used for online recovery method or the Direct image flash one?

**Comment by Mo-5590** [comment]
Hi Sorry for the late i'm not always online
here you can see a lot of help
Good luck 
And Thank you
https://www.hackintosh-forum.de/forum/thread/51618-oc-dell-latitude-e6420/

**Comment by HimanshuRane** [comment]
i am stilling facing issues, is there any other way i can get in touch with u, telegram or anyother method?

**Comment by Mo-5590** [comment]
First sorry again
Second i have an easy method:
1 Install any macos: high sierra, mojave or catalina
2 creat a partition ms fat32 in your hard disk. This partition will be the EFI od your macOS Big Sur and put the folder OC (OpenCore) in It
3 After that go to the Bios and creat a boot with this new partition and the folder Efi OC
4 Prepare your USB macOS big sur and install it with the OC folder
Finally, Good luck and thank you very much

**Comment by HimanshuRane** [comment]
nah dont be sry its all right,
actually i have bot level basic issues like how are u making the usb i tired by OC oline recovery but it failed then i tired image but it didnt boot idk which image u used or soo.

**Comment by Mo-5590** [comment]
Don't worry in this case i will show you step by step how install macOS Big Sur in your own dell latitude E6420 with pictures OK....
But I have a small problem i don't know how putting these pictures here so i will send a forum where i do these for you Ok...
https://www.hackintosh-forum.de/forum/thread/51618-oc-dell-latitude-e6420/

**Comment by HimanshuRane** [comment]
Thxss that will be a gr8 help🙌

**Comment by Mo-5590** [comment]
Not at all you're welcome...thx too
